# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Lexanne Painter
# Description of the Site
description: All about me
# URL of Image of the Site
site-image: /WhatATheme/assets/images/martin-franco-kmafxTVsfG8-unsplash.jpg
# Keywords of the Site
site-keywords: 
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /WhatATheme/assets/images/martin-franco-kmafxTVsfG8-unsplash.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: me@lexanne.io
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: lexanne
github_username:  
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Lexanne Painter
# URL for the Image of the Author
author-image: https://media.licdn.com/dms/image/v2/C4D03AQG7rMoiJBQLKg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1547218821098?e=1729123200&v=beta&t=FbjD0VeJUmbZm-I4MRpyHxxEnrdhv4EARdEgZF-f6FY
# 60 Words About the Author
author-about: Experienced customer support technical lead for selfhosted data quality software implemented on distributed systems and Kubernetes clusters
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
